In [68]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import cross_val_score, RandomizedSearchCV, GridSearchCV, cross_validate, RepeatedKFold
from sklearn.metrics import mean_squared_error, r2_score, mean_absolute_error, median_absolute_error
from matplotlib.pyplot import figure
from sklearn.model_selection import train_test_split
from sklearn.model_selection import RepeatedKFold
from sklearn.tree import plot_tree
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report
from sklearn.metrics import accuracy_score, log_loss
from sklearn.model_selection import cross_val_predict
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report

# Dataset generation

## Test

### Mild Dementia

In [2]:
import glob
from PIL import Image
import numpy as np

result = []
counter = 0
    
for k in glob.glob(r'C:\Users\italo\OneDrive\Desktop\alzheimer\Alzheimer_s Dataset\test\MildDemented\*.jpg'):
    im = Image.open(k)
    im = im.reduce(40)
    pixels = im.getdata()  
    for pixel in pixels:
        counter += 1
        if type(pixel) == int:
            pixel = (pixel,pixel,pixel)
    #result.append(pixel[1])
            result.append(int((pixel[0]+pixel[1]+pixel[2])/3))

#print(result[:9160])
print(len(result))
            #result.append(pixel[1])
#print(result[0:400])
#print(len(result)) #1638208 = 9152*179
test_mild_array = np.array(result)  
test_mild_array = test_mild_array.reshape((179, 30)) #vedi bene QUESTO
#mask = (a > 0)
#print(test_mild_array)
#print(test_mild_array[0])
#extract_from_a = test_mild_array[0][mask] # or,  a[a%3==0]
#print(extract_from_a)
#test_mild_array.shape
#test_mild_array = pd.DataFrame(test_mild_array)
csv_test_mild = r'C:\Users\italo\OneDrive\Desktop\csv_test_mild.csv' 
#test_mild_array.to_csv(r'C:\Users\italo\OneDrive\Desktop\prova.csv
np.savetxt(csv_test_mild, test_mild_array, fmt="%d", delimiter=",")

5370

### Moderate Dementia

In [3]:
result = []
counter = 0
    
for k in glob.glob(r'C:\Users\italo\OneDrive\Desktop\alzheimer\Alzheimer_s Dataset\test\ModerateDemented\*.jpg'):
    im = Image.open(k)
    im = im.reduce(40)
    pixels = im.getdata()  
    for pixel in pixels:
        counter += 1
        if type(pixel) == int:
            pixel = (pixel,pixel,pixel)
            result.append(int((pixel[0]+pixel[1]+pixel[2])/3))
            
test_moderate_array = np.array(result)
test_moderate_array = test_moderate_array.reshape((12, 30)) 
csv_test_moderate = r'C:\Users\italo\OneDrive\Desktop\csv_test_moderate.csv'
np.savetxt(csv_test_moderate, test_moderate_array, fmt="%d", delimiter=",")

### Non Dementia

In [4]:
result = []
counter = 0
    
for k in glob.glob(r'C:\Users\italo\OneDrive\Desktop\alzheimer\Alzheimer_s Dataset\test\NonDemented\*.jpg'):
    im = Image.open(k)
    im = im.reduce(40)
    pixels = im.getdata()  
    for pixel in pixels:
        counter += 1
        if type(pixel) == int:
            pixel = (pixel,pixel,pixel)
            result.append(int((pixel[0]+pixel[1]+pixel[2])/3))
            
test_non_array = np.array(result)
test_non_array = test_non_array.reshape((640, 30)) 
csv_test_non = r'C:\Users\italo\OneDrive\Desktop\csv_test_non.csv'
np.savetxt(csv_test_non, test_non_array, fmt="%d", delimiter=",")

### Very Mild Dementia

In [5]:
result = []
counter = 0
    
for k in glob.glob(r'C:\Users\italo\OneDrive\Desktop\alzheimer\Alzheimer_s Dataset\test\VeryMildDemented\*.jpg'):
    im = Image.open(k)
    im = im.reduce(40)
    pixels = im.getdata()  
    for pixel in pixels:
        counter += 1
        if type(pixel) == int:
            pixel = (pixel,pixel,pixel)
            result.append(int((pixel[0]+pixel[1]+pixel[2])/3))
            
test_very_array = np.array(result)
test_very_array = test_very_array.reshape((448, 30)) 
csv_test_very = r'C:\Users\italo\OneDrive\Desktop\csv_test_very.csv'
np.savetxt(csv_test_very, test_very_array, fmt="%d", delimiter=",")

## Train

### Mild Dementia

In [6]:
result = []
counter = 0
    
for k in glob.glob(r'C:\Users\italo\OneDrive\Desktop\alzheimer\Alzheimer_s Dataset\train\MildDemented\*.jpg'):
    im = Image.open(k)
    im = im.reduce(40)
    pixels = im.getdata()  
    for pixel in pixels:
        counter += 1
        if type(pixel) == int:
            pixel = (pixel,pixel,pixel)
            result.append(int((pixel[0]+pixel[1]+pixel[2])/3))
            
train_mild_array = np.array(result)
train_mild_array = train_mild_array.reshape((717, 30)) 
csv_train_mild = r'C:\Users\italo\OneDrive\Desktop\csv_train_mild.csv'
np.savetxt(csv_train_mild, train_mild_array, fmt="%d", delimiter=",")

### Moderate Dementia

In [7]:
result = []
counter = 0
    
for k in glob.glob(r'C:\Users\italo\OneDrive\Desktop\alzheimer\Alzheimer_s Dataset\train\ModerateDemented\*.jpg'):
    im = Image.open(k)
    im = im.reduce(40)
    pixels = im.getdata()  
    for pixel in pixels:
        counter += 1
        if type(pixel) == int:
            pixel = (pixel,pixel,pixel)
            result.append(int((pixel[0]+pixel[1]+pixel[2])/3))
            
train_moderate_array = np.array(result)
train_moderate_array = train_moderate_array.reshape((52, 30)) 
csv_train_moderate = r'C:\Users\italo\OneDrive\Desktop\csv_train_moderate.csv'
np.savetxt(csv_train_moderate, train_moderate_array, fmt="%d", delimiter=",")

### Non Dementia

In [8]:
result = []
counter = 0
    
for k in glob.glob(r'C:\Users\italo\OneDrive\Desktop\alzheimer\Alzheimer_s Dataset\train\NonDemented\*.jpg'):
    im = Image.open(k)
    im = im.reduce(40)
    pixels = im.getdata()  
    for pixel in pixels:
        counter += 1
        if type(pixel) == int:
            pixel = (pixel,pixel,pixel)
            result.append(int((pixel[0]+pixel[1]+pixel[2])/3))
            
train_non_array = np.array(result)
train_non_array = train_non_array.reshape((2560, 30)) 
csv_train_non = r'C:\Users\italo\OneDrive\Desktop\csv_train_non.csv'
np.savetxt(csv_train_non, train_non_array, fmt="%d", delimiter=",")

### Very Mild Dementia

In [9]:
result = []
counter = 0
    
for k in glob.glob(r'C:\Users\italo\OneDrive\Desktop\alzheimer\Alzheimer_s Dataset\train\VeryMildDemented\*.jpg'):
    im = Image.open(k)
    im = im.reduce(40)
    pixels = im.getdata()  
    for pixel in pixels:
        counter += 1
        if type(pixel) == int:
            pixel = (pixel,pixel,pixel)
            result.append(int((pixel[0]+pixel[1]+pixel[2])/3))
            
train_very_array = np.array(result)
train_very_array = train_very_array.reshape((1792, 30)) 
csv_train_very = r'C:\Users\italo\OneDrive\Desktop\csv_train_very.csv'
np.savetxt(csv_train_very, train_very_array, fmt="%d", delimiter=",")

In [10]:
#code for a single image
#import pandas as pd
#im = Image.open(r'C:\Users\italo\OneDrive\Desktop\lena.jpg')
#im = im.reduce(2)
#pixels = im.getdata()
#result = []
#counter = 0
#for pixel in pixels:
    #counter += 1
    #if type(pixel) == int:
        #pixel = (pixel,pixel,pixel)
    #result.append(pixel[1])
    #result.append(pixel[1])

## adding variable 'label'

In [11]:
import pandas as pd

### test - non

In [12]:
directory = r'C:\Users\italo\OneDrive\Desktop'
file = 'csv_test_non.csv'
df_test_non = pd.read_csv(f'{directory}/{file}')

In [13]:
non_label = np.array([0 for i in range (639)]) #we create a an array with all 0
non_label = non_label.T #transposes array
#non_label.shape
non_label = pd.DataFrame(non_label) #transforms in a pandas object to me concateneted with this library

In [14]:
non_labelized_test = pd.concat([df_test_non, non_label], axis=1) #concats per column
non_labelized_test.rename(columns = {non_labelized_test.columns[-1]:'label'}) #renames last variable

,0,28,39,4,0.1,35,173,167,99,0.2,...,74,78,14,0.6,0.7,0.8,0.9,0.10,0.11,label
0,0,35,48,5,0,33,190,184,105,0,...,62,73,13,0,0,0,0,0,0,0
1,0,32,45,4,0,38,185,178,99,0,...,78,80,14,0,0,0,0,0,0,0
2,0,26,37,3,0,32,156,148,79,0,...,59,67,13,0,0,0,0,0,0,0
3,0,36,48,5,0,34,160,156,92,0,...,64,69,11,0,0,0,0,0,0,0
4,0,31,49,6,0,38,185,178,107,0,...,74,85,15,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
634,0,22,38,2,0,38,195,185,122,0,...,76,82,11,0,0,0,0,0,0,0
635,0,19,40,2,0,37,175,181,97,0,...,64,74,7,0,0,0,0,0,0,0
636,0,24,35,2,0,25,174,150,88,0,...,60,72,11,0,0,0,0,0,0,0
637,0,26,35,2,0,29,169,170,92,0,...,58,61,8,0,0,0,0,0,0,0
638,0,22,30,2,0,30,171,162,94,0,...,60,76,8,0,0,0,0,0,0,0

### test - very

In [15]:
directory = r'C:\Users\italo\OneDrive\Desktop'
file = 'csv_test_very.csv'
df_test_very = pd.read_csv(f'{directory}/{file}')
very_label = np.array([1 for i in range (447)])
very_label = very_label.T
very_label = pd.DataFrame(very_label)
very_labelized_test = pd.concat([df_test_very, very_label], axis=1)
very_labelized_test.rename(columns = {very_labelized_test.columns[-1]:'label'})

,0,26,40,3,0.1,37,174,166,97,0.2,...,73,81,11,0.6,0.7,0.8,0.9,0.10,0.11,label
0,0,27,42,3,0,33,187,177,90,0,...,83,81,13,0,0,0,0,0,0,1
1,0,18,25,2,0,23,114,109,55,0,...,45,47,9,0,0,0,0,0,0,1
2,0,26,34,4,0,23,154,151,82,0,...,65,70,13,0,0,0,0,0,0,1
3,0,39,45,4,0,38,179,172,90,0,...,79,75,13,0,0,0,0,0,0,1
4,0,39,53,4,0,37,189,177,113,0,...,82,81,15,0,0,0,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
442,0,25,33,3,0,38,185,182,94,0,...,65,66,8,0,0,0,0,0,0,1
443,0,18,27,2,0,21,102,98,56,0,...,40,45,7,0,0,0,0,0,0,1
444,0,27,34,2,0,33,188,183,84,0,...,59,69,8,0,0,0,0,0,0,1
445,0,20,28,2,0,27,159,154,92,0,...,59,70,11,0,0,0,0,0,0,1
446,0,23,32,1,0,31,164,164,91,0,...,56,72,8,0,0,0,0,0,0,1

### test - mild

In [16]:
directory = r'C:\Users\italo\OneDrive\Desktop'
file = 'csv_test_mild.csv'
df_test_mild = pd.read_csv(f'{directory}/{file}')
mild_label = np.array([2 for i in range (178)])
mild_label = mild_label.T
mild_label = pd.DataFrame(mild_label)
mild_labelized_test = pd.concat([df_test_mild, mild_label], axis=1)
mild_labelized_test.rename(columns = {mild_labelized_test.columns[-1]:'label'})

,0,27,41,2,0.1,36,181,155,94,0.2,...,68.1,74,13,0.6,0.7,0.8,0.9,0.10,0.11,label
0,0,31,45,4,0,34,163,157,101,0,...,70,73,13,0,0,0,0,0,0,2
1,0,33,44,5,0,36,158,142,99,0,...,75,85,11,0,0,0,0,0,0,2
2,0,35,49,4,0,33,169,157,93,0,...,74,76,15,0,0,0,0,0,0,2
3,0,23,33,3,0,29,118,111,64,0,...,58,56,12,0,0,0,0,0,0,2
4,0,33,46,5,0,36,155,142,98,0,...,61,74,12,0,0,0,0,0,0,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
173,0,20,32,2,0,35,163,153,81,0,...,56,56,9,0,0,0,0,0,0,2
174,0,20,34,2,0,32,168,163,95,0,...,45,50,9,0,0,0,0,0,0,2
175,0,13,27,1,0,25,145,150,85,0,...,45,57,7,0,0,0,0,0,0,2
176,0,18,22,1,0,35,174,159,95,0,...,54,63,9,0,0,0,0,0,0,2
177,0,21,27,2,0,34,179,151,100,0,...,59,68,9,0,0,0,0,0,0,2

### test - moderate

In [31]:
directory = r'C:\Users\italo\OneDrive\Desktop'
file = 'csv_test_moderate.csv'
df_test_moderate = pd.read_csv(f'{directory}/{file}')
moderate_label = np.array([3 for i in range (11)])
moderate_label = moderate_label.T
moderate_label = pd.DataFrame(moderate_label)
moderate_labelized_test = pd.concat([df_test_moderate, moderate_label], axis=1)
moderate_labelized_test.rename(columns = {moderate_labelized_test.columns[-1]:'label'})

,0,29,32,4,0.1,35,158,147,101,0.2,...,64,74,13,0.6,0.7,0.8,0.9,0.10,0.11,label
0,0,28,48,4,0,33,185,167,105,0,...,78,74,13,0,0,0,0,0,0,3
1,0,27,33,4,0,35,159,145,100,0,...,61,75,11,0,0,0,0,0,0,3
2,0,26,46,3,0,32,188,170,103,0,...,76,72,13,0,0,0,0,0,0,3
3,0,24,33,3,0,33,158,143,99,0,...,61,75,10,0,0,0,0,0,0,3
4,0,22,42,3,0,31,183,168,98,0,...,72,68,13,0,0,0,0,0,0,3
5,0,23,33,3,0,33,158,140,99,0,...,64,75,8,0,0,0,0,0,0,3
6,0,20,41,3,0,32,182,175,98,0,...,71,68,14,0,0,0,0,0,0,3
7,0,21,31,3,0,32,156,135,96,0,...,65,73,6,0,0,0,0,0,0,3
8,0,17,37,2,0,32,174,174,94,0,...,68,68,13,0,0,0,0,0,0,3
9,0,20,30,2,0,32,158,132,95,0,...,65,70,6,0,0,0,0,0,0,3
10,0,17,34,2,0,32,167,170,90,0,...,66,68,12,0,0,0,0,0,0,3

### train - non

In [18]:
directory = r'C:\Users\italo\OneDrive\Desktop'
file = 'csv_train_non.csv'
df_test_non = pd.read_csv(f'{directory}/{file}')
non_label = np.array([0 for i in range (2559)])
non_label = non_label.T
non_label = pd.DataFrame(non_label)
non_labelized_train = pd.concat([df_test_non, non_label], axis=1)
non_labelized_train.rename(columns = {non_labelized_train.columns[-1]:'label'})

,0,61,77,10,0.1,45,181,134,107,0.2,...,99,99.1,22,0.5,0.6,0.7,0.8,0.9,0.10,label
0,0,51,60,10,0,39,145,121,97,0,...,66,77,16,0,0,0,0,0,0,0
1,0,58,83,12,0,47,181,159,130,0,...,101,97,23,0,0,0,0,0,0,0
2,0,60,78,10,0,43,177,129,104,0,...,100,100,22,0,0,0,0,0,0,0
3,0,60,70,7,0,40,163,148,113,0,...,84,91,18,0,0,0,0,0,0,0
4,0,45,61,7,0,36,147,118,98,0,...,74,79,14,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2554,0,53,61,9,0,34,143,125,102,0,...,86,96,20,0,0,0,0,0,0,0
2555,0,64,76,10,0,46,164,139,105,0,...,93,106,22,0,0,0,0,0,0,0
2556,0,50,73,8,0,34,136,121,93,0,...,93,96,20,0,0,0,0,0,0,0
2557,0,58,80,10,0,49,164,135,120,0,...,90,97,24,0,0,0,0,0,0,0
2558,0,58,73,9,0,39,162,127,96,0,...,83,98,21,0,0,0,0,0,0,0

### train - very

In [19]:
directory = r'C:\Users\italo\OneDrive\Desktop'
file = 'csv_train_very.csv'
df_test_very = pd.read_csv(f'{directory}/{file}')
very_label = np.array([1 for i in range (1791)])
very_label = very_label.T
very_label = pd.DataFrame(very_label)
very_labelized_train = pd.concat([df_test_very, very_label], axis=1)
very_labelized_train.rename(columns = {very_labelized_train.columns[-1]:'label'})

,0,67,66,8,0.1,43,170,143,104,0.2,...,88,89,21,0.5,0.6,0.7,0.8,0.9,0.10,label
0,0,66,72,9,0,40,151,147,100,0,...,87,88,21,0,0,0,0,0,0,1
1,0,68,72,11,0,45,183,155,113,0,...,93,95,21,0,0,0,0,0,0,1
2,0,53,63,8,0,37,150,120,82,0,...,75,85,19,0,0,0,0,0,0,1
3,0,51,61,7,0,37,160,151,108,0,...,76,88,23,0,0,0,0,0,0,1
4,0,48,67,6,0,35,153,140,103,0,...,82,84,19,0,0,0,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1786,0,47,67,6,0,43,168,154,97,0,...,92,82,14,0,0,0,0,0,0,1
1787,0,49,57,7,0,37,161,143,93,0,...,84,94,19,0,0,0,0,0,0,1
1788,0,48,57,7,0,31,163,146,98,0,...,76,84,21,0,0,0,0,0,0,1
1789,0,54,73,8,0,44,163,139,98,0,...,87,94,19,0,0,0,0,0,0,1
1790,0,50,62,7,0,37,134,130,101,0,...,85,81,16,0,0,0,0,0,0,1

### train - mild

In [20]:
directory = r'C:\Users\italo\OneDrive\Desktop'
file = 'csv_train_mild.csv'
df_test_mild = pd.read_csv(f'{directory}/{file}')
mild_label = np.array([2 for i in range (716)])
mild_label = mild_label.T
mild_label = pd.DataFrame(mild_label)
mild_labelized_train = pd.concat([df_test_mild, mild_label], axis=1)
mild_labelized_train.rename(columns = {mild_labelized_train.columns[-1]:'label'})

,0,37,43,6,0.1,28,112,80,57,0.2,...,61,58,12,0.5,0.6,0.7,0.8,0.9,0.10,label
0,0,59,75,7,0,42,154,134,98,0,...,81,88,18,0,0,0,0,0,0,2
1,0,52,66,7,0,43,142,94,87,0,...,81,80,15,0,0,0,0,0,0,2
2,0,59,81,8,0,40,141,112,99,0,...,80,80,21,0,0,0,0,0,0,2
3,0,48,57,11,0,34,83,94,80,0,...,76,78,19,0,0,0,0,0,0,2
4,0,54,71,8,0,30,154,141,100,0,...,85,86,20,0,0,0,0,0,0,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
711,0,60,67,8,0,39,154,114,89,0,...,86,84,20,0,0,0,0,0,0,2
712,0,62,67,10,0,50,138,92,94,0,...,91,102,24,0,0,0,0,0,0,2
713,1,59,71,12,0,44,161,120,113,0,...,91,98,22,0,0,0,0,0,0,2
714,1,57,73,9,0,47,164,122,101,0,...,95,91,26,0,0,0,0,0,0,2
715,0,62,69,11,0,45,147,107,110,0,...,88,92,20,0,0,0,0,0,0,2

### train - moderate

In [30]:
directory = r'C:\Users\italo\OneDrive\Desktop'
file = 'csv_train_moderate.csv'
df_test_moderate = pd.read_csv(f'{directory}/{file}')
moderate_label = np.array([3 for i in range (51)])
moderate_label = moderate_label.T
moderate_label = pd.DataFrame(moderate_label)
moderate_labelized_train = pd.concat([df_test_moderate, moderate_label], axis=1)
moderate_labelized_train.rename(columns = {moderate_labelized_train.columns[-1]:'label'})
moderate_labelized_train.head() #here we use head because otherwise would have printed all dataset

,0,56,61,6,0.1,34,146,105,81,0.2,...,78,75,16,0.5,0.6,0.7,0.8,0.9,0.10,0
0,0,60,73,10,0,48,179,145,108,0,...,91,91,27,0,0,0,0,0,0,3
1,0,57,72,9,0,42,134,119,96,0,...,88,87,24,0,0,0,0,0,0,3
2,0,50,68,9,0,35,144,119,93,0,...,93,90,24,0,0,0,0,0,0,3
3,0,57,73,9,0,43,139,124,95,0,...,87,90,23,0,0,0,0,0,0,3
4,0,53,70,9,0,36,150,125,101,0,...,96,93,24,0,0,0,0,0,0,3

## Merging dfs

In [52]:
a = np.array(non_labelized_test)
e = np.array(non_labelized_train)
non = np.concatenate((a, e), axis=0)
non = non[:1600, :]
non.shape

(1600, 31)

In [50]:
b = np.array(very_labelized_test)
f = np.array(very_labelized_train)
very_mild = np.concatenate((b, f), axis=0)
very_mild = very_mild[:1600, :]
very_mild.shape
#print(very_mild)

(1600, 31)

In [51]:
c = np.array(mild_labelized_test)
g = np.array(mild_labelized_train)
mild = np.concatenate((c, g), axis = 0)
mild = np.concatenate((mild, mild), axis = 0) 
mild = mild[:1600, :]
mild.shape
#print(mild)

(1600, 31)

In [43]:
d = np.array(moderate_labelized_test)
h = np.array(moderate_labelized_train)
moderate = np.concatenate((d, h), axis = 0)
moderate = np.concatenate((moderate,moderate,moderate,moderate,moderate,moderate,moderate,moderate,moderate,moderate,moderate,moderate,moderate,moderate,moderate,moderate,moderate,moderate,moderate,moderate,moderate,moderate,moderate,moderate,moderate,moderate,moderate,), axis = 0) 
moderate = moderate[:1600, :]
print(moderate.shape)

(1600, 31)

In [44]:
#use numpy to concatenate dataframes in one
array = np.concatenate((non, very_mild, mild, moderate), axis = 0) #concatenates per row
#array.shape

In [45]:
#use numpy to save these data in csv format
path = r'C:\Users\italo\OneDrive\Desktop\PIXEL\Reduce_40\table.csv'
np.savetxt(path, array, fmt="%d", delimiter=",")

In [46]:
directory = r'C:\Users\italo\OneDrive\Desktop\PIXEL\Reduce_40'
file = 'table.csv'
df = pd.read_csv(f'{directory}/{file}')

In [47]:
df[df.columns[-1]] = df[df.columns[-1]].apply(lambda x: float(x))

In [48]:
X = df.loc[:, df.columns != df.columns[-1]].values
y = df.loc[:, df.columns == df.columns[-1]].values
y = y.ravel()
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=0)

In [49]:
y.shape

(6399,)

In [53]:
cv = RepeatedKFold(n_splits=10, n_repeats=3, random_state=30)

## Decision Tree Classifier

In [67]:
# Function to perform training with giniIndex. 
def train_using_gini(X_train, X_test, y_train): 
  
    # Creating the classifier object 
    clf_gini = DecisionTreeClassifier(criterion = "gini", 
            random_state = 100,max_depth=3, min_samples_leaf=5) 
  
    # Performing training 
    clf_gini.fit(X_train, y_train) 
    return clf_gini 
      
# Function to perform training with entropy. 
def tarin_using_entropy(X_train, X_test, y_train): 
  
    # Decision tree with entropy 
    clf_entropy = DecisionTreeClassifier( 
            criterion = "entropy", random_state = 100, 
            max_depth = 3, min_samples_leaf = 5) 
  
    # Performing training 
    clf_entropy.fit(X_train, y_train) 
    return clf_entropy 

def prediction(X_test, clf_object): 
  
    # Predicton on test with giniIndex 
    y_pred = clf_object.predict(X_test) 
    print("Predicted values:") 
    print(y_pred) 
    return y_pred 
      
# Function to calculate accuracy 
def cal_accuracy(y_test, y_pred): 
      
    print("Confusion Matrix: ", 
        confusion_matrix(y_test, y_pred)) 
      
    print ("Accuracy : ", 
    accuracy_score(y_test,y_pred)*100) 
      
    print("Report : ", 
    classification_report(y_test, y_pred)) 
    
# Driver code 
def main(): 
      
    # Building Phase 
    #data = importdata() 
    #X, Y, X_train, X_test, y_train, y_test = splitdataset(data) 
    clf_gini = train_using_gini(X_train, X_test, y_train) 
    clf_entropy = tarin_using_entropy(X_train, X_test, y_train) 
      
    # Operational Phase 
    print("Results Using Gini Index:") 
      
    # Prediction using gini 
    y_pred_gini = prediction(X_test, clf_gini) 
    cal_accuracy(y_test, y_pred_gini) 
      
    print("Results Using Entropy:") 
    # Prediction using entropy 
    y_pred_entropy = prediction(X_test, clf_entropy) 
    cal_accuracy(y_test, y_pred_entropy) 
      
      # Calling main function 
if __name__=="__main__": 
    main()

Results Using Gini Index:
Predicted values:
[1. 3. 3. ... 0. 3. 1.]
Confusion Matrix:  [[260 148  25  50]
 [ 58 282  66  75]
 [ 18 276  55 119]
 [  0 153   0 335]]
Accuracy :  48.541666666666664
Report :                precision    recall  f1-score   support

         0.0       0.77      0.54      0.63       483
         1.0       0.33      0.59      0.42       481
         2.0       0.38      0.12      0.18       468
         3.0       0.58      0.69      0.63       488

    accuracy                           0.49      1920
   macro avg       0.51      0.48      0.47      1920
weighted avg       0.52      0.49      0.47      1920

Results Using Entropy:
Predicted values:
[2. 3. 3. ... 2. 3. 0.]
Confusion Matrix:  [[287   0 167  29]
 [103   0 316  62]
 [ 37   0 319 112]
 [  0   0 153 335]]
Accuracy :  49.010416666666664
Report :                precision    recall  f1-score   support

         0.0       0.67      0.59      0.63       483
         1.0       0.00      0.00      0.00       481
         2.0       0.33      0.68      0.45       468
         3.0       0.62      0.69      0.65       488

    accuracy                           0.49      1920
   macro avg       0.41      0.49      0.43      1920
weighted avg       0.41      0.49      0.43      1920

C:\Users\italo\miniconda3\envs\exams\lib\site-packages\sklearn\metrics\_classification.py:1221: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))